/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author it21233
 */
public class mainBox extends javax.swing.JFrame {
    
    /**
     * Creates new form mainBox
     */
    public mainBox() {
        initComponents();
        String via;
        String sch;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();        
        for(int i = 0;i<DemoGUI.table.size();i++) {
            if(DemoGUI.table.get(i).getVia()==null) {
                via=null;
            }
            else {
                via = DemoGUI.table.get(i).getVia();
            }
            if(DemoGUI.table.get(i).getExpected_Departure()==null){
                sch = null;
            }
            else {
                sch = DemoGUI.table.get(i).getExpected_Departure().toString();
            }
            
            model.addRow(new Object[] {
                DemoGUI.table.get(i).getDeparture(),
                DemoGUI.table.get(i).getAirline_Name(), 
                DemoGUI.table.get(i).getCode(), 
                via, 
                sch, 
                DemoGUI.table.get(i).getScheduled_Departure().toString(), 
                DemoGUI.table.get(i).getRemarks()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 530));
        setPreferredSize(new java.awt.Dimension(640, 480));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departures", "Airline", "Flight", "Via", "Expected Departure", "Scheduled Departure", "Remarks"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add Airline");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Flight");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit Airline");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Airline");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Edit Flight");

        jButton6.setText("Delete Flight");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getAirline.main(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(DemoGUI.tableAir.size()==0) {
            JOptionPane.showMessageDialog(null, "Insert a Airline first.");
            return;
        }
        
        getFlight.main(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() == -1)
            return;
                    
        basics.Flight flight;
        ArrayList<Object> value = new ArrayList<>();
        int row = jTable1.getSelectedRow();
        int column = jTable1.getColumnCount();
        for(int i = 0; i < column; i++) {
                value.add(jTable1.getValueAt(row, i));
        }    
        
        System.out.println(Timestamp.valueOf((String) value.get(4)).toString());
        flight = new basics.Flight((String)value.get(0), (String)value.get(1), (String)value.get(2), (String)value.get(3), Timestamp.valueOf((String) value.get(4)), Timestamp.valueOf((String) value.get(5)), (String)value.get(6));
        
        DefaultTableModel model = (DefaultTableModel) gui.mainBox.jTable1.getModel();
        if(jTable1.getSelectedRow() != -1) {
            model.removeRow(jTable1.getSelectedRow());
        }
        
        for(int i=0;i<gui.DemoGUI.table.size();i++) {
            if(((String) value.get(2)).equals(gui.DemoGUI.table.get(i).getCode())) {
                gui.DemoGUI.table.remove(i);
                break;
            }
        }
        
        for(int i=0;i<gui.DemoGUI.tableAir.size();i++) {
            for(int j=0;j<gui.DemoGUI.tableAir.get(i).getFlights().size();j++) {
                if(((String) value.get(2)).equals(gui.DemoGUI.table.get(i).getCode())) {
                    gui.DemoGUI.tableAir.get(i).getFlights().remove(j);
                    break;
                }
            }
        }
        
        database.DatabaseConnector dbcon = new database.DatabaseConnector();
        dbcon.deleteObject(flight);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model;
        int row;
        int column;
        if(jTable1.getSelectedRow() == -1)
            return;
                    
        basics.Flight flight;
        int myrow = jTable1.getSelectedRow();
        String airline_name = (String) jTable1.getValueAt(myrow, 1); 
        
        for(int i=jTable1.getRowCount()-1;i>=0;i--){
            if(jTable1.getValueAt(i, 1).equals(airline_name)){
                model = (DefaultTableModel) gui.mainBox.jTable1.getModel();
                model.removeRow(i);
            }
        }
        
        for(int i=gui.DemoGUI.tableAir.size()-1;i>=0;i--) {
            for(int j=gui.DemoGUI.tableAir.get(i).getFlights().size()-1;j>=0;j--) {
                if(gui.DemoGUI.tableAir.get(i).getFlights().get(j).getAirline_Name().equals(airline_name)) {
                    gui.DemoGUI.tableAir.get(i).getFlights().remove(j);
                }
            }
        }
        
        for(int i=gui.DemoGUI.table.size()-1;i>=0;i--) {
            if(gui.DemoGUI.table.get(i).equals(airline_name)) {
                gui.DemoGUI.table.remove(i);
            }
        }
        
        database.DatabaseConnector dbcon = new database.DatabaseConnector();
        dbcon.deleteObject(airline_name);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainBox().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
